name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: snap
          POSTGRES_PASSWORD: snap_password
          POSTGRES_DB: snap
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U snap -d snap"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 12.9.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm db:generate
        env:
          DATABASE_URL: postgresql://snap:snap_password@localhost:5432/snap

      - name: Run Prisma migrations
        run: pnpm --filter @snap/database exec prisma migrate deploy
        env:
          DATABASE_URL: postgresql://snap:snap_password@localhost:5432/snap

      - name: Typescript
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
